### ISSUE TITLE
what's the purpose of restricted_viterbi_decode and marginal_probabilities

### ISSUE THREAD

**Issue by xilinniao123** [kajyuuen/pytorch-partial-crf#10]
thans for sharing!
what's the purpose of restricted_viterbi_decode and marginal_probabilities

**Comment by kajyuuen** [comment]
Thank you for the question.

`restricted_viterbi_decode` can be specify the paths that is able to pass through.For example, if a word is already registered as an S-LOC, viterbi decodes You can specify that you must pass through it when.
`marginal_probabilities` is the probability that each word is tagged with a You can make it output. This is designed to be used for data analysis and co-training.
