### ISSUE TITLE
Add possible tags restriction for missing annotations

### ISSUE THREAD

**Issue by viktor-shcherb** [kajyuuen/pytorch-partial-crf#13]
At the moment missing annotations (-1 tag) are treated as all possible tags.

I experiment with removing noise from partial annotations by matching samples from unannotated corpus with set of quality phrases that are considered to be some sort of entity (removing O tag from possible tag space). It seems to have worked for [Farhad Nooralahzadeh et al](https://www.duo.uio.no/bitstream/handle/10852/78169/1/D19-6125%2B%25282%2529.pdf#page=6&zoom=100,209,382).

I will probably just modify your code by myself, but maybe I'm not the only one who needs this functionality.

**Comment by kajyuuen** [comment]
Thank you for your idea.
I've implemented a similar CRF before, so I think I'll add it.
It was implemented quite a while ago, so if there is any behavior you are interested in, it would be great if you could send me a PR.
