### ISSUE TITLE
Difference between MarginalCRF and PartialCRF

### ISSUE THREAD

**Issue by viktor-shcherb** [kajyuuen/pytorch-partial-crf#18]
Correct me if I'm wrong but isn't `MarginalCRF` just a generalized version of `PartialCRF`? Is the latter implemented just for convenience purposes?

I think of swapping unknown tags (-1) of `PartialCRF` with uniform distribution over tags for `MarginalCRF` and converting other indexes to one-hot float tensors. Would there be any obvious downfalls with this transition to `MarginalCRF` I don't see?

If you haven't tested this scenario but still have any thoughts on the matter, please share! You clearly have more experience working with CRFs so any input will be appreciated.

Thanks in advance!

**Comment by kajyuuen** [comment]
You just said it.
MarginalCRF tests implement code to see if it works as well as PartialCRF.
https://github.com/kajyuuen/pytorch-partial-crf/blob/master/tests/test_marginal_crf.py#L104

However, MarginalCRF is more computationally intensive and may be a bit slower than PartialCRF.
So the question of whether or not to replace this is quite difficult.
I think it's worth measuring the execution speed and replacing it if there is not that much difference.

**Comment by kajyuuen** [comment]
I appreciate your comments on this library.
I'm sure there are still various improvements to be made, so it would be great if you could make another PR or Issue.
