### ISSUE TITLE
question about the pad_idx

### ISSUE THREAD

**Issue by yangshao** [kajyuuen/pytorch-partial-crf#9]
Hi, does the pad_idx means the padding tag's index? if so, does the num_tags include this pad_idx?

**Comment by kajyuuen** [comment]
Thank you for your question.
If you don't pass anything to CRF optional argument padding_idx, you don't need to include it in num_tag; if you specify padding tag's index for padding_idx, you need to increment num_tag for padding tag.

**Comment by kajyuuen** [comment]
@yangshao
